In [1]:
import codecs
import random

import numpy as np
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
stopwords = codecs.open("hindi_stopwords.txt", "r", encoding='utf-8', errors='ignore').read().split('\n')

In [5]:
def get_features(type='dbn'):
    pos_hindi_reviews = codecs.open("pos_hindi.txt", "r", encoding='utf-8', errors='ignore').read()
    neg_hindi_reviews = codecs.open("neg_hindi.txt", "r", encoding='utf-8', errors='ignore').read()
    pos_eng_reviews = codecs.open("pos_eng.txt", "r", encoding='utf-8', errors='ignore').read()
    neg_eng_reviews = codecs.open("neg_eng.txt", "r", encoding='utf-8', errors='ignore').read()
    documents = []
    
    pos_count = 0
    for i in pos_hindi_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            pos_count += 1
    neg_count = 0
    for i in neg_hindi_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            neg_count += 1
            
    for i in pos_eng_reviews.split(' .'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            pos_count += 1
    for i in neg_eng_reviews.split(' .'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            neg_count += 1
            
    vectorizer = TfidfVectorizer(lowercase=False, analyzer=word_tokenize)
    tfidf = vectorizer.fit_transform(documents)
    featureset = tfidf.toarray()
    positive_feature_set = featureset[0:pos_count]
    negative_set = featureset[pos_count:]
    finalset = []
    for i in positive_feature_set:
        if type == 'simple':
            finalset.append([i, [1, 0]])
        else:
            finalset.append([i, 1])
    for i in negative_set:
        if type == 'simple':
            finalset.append([i, [0, 1]])
        else:
            finalset.append([i, 0])
    finalset = np.array(finalset)
    random.shuffle(finalset)
    test_size = 0.1
    testing_size = int((1 - test_size) * len(finalset))
    x_train = list(finalset[:, 0][:testing_size])
    y_train = list(finalset[:, 1][:testing_size])
    x_test = list(finalset[:, 0][testing_size:])
    y_test = list(finalset[:, 1][testing_size:])
    return x_train, y_train
    
get_features()

MemoryError: 

In [3]:
import codecs
import random

import numpy as np
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

stopwords = codecs.open("hindi_stopwords.txt", "r", encoding='utf-8', errors='ignore').read().split('\n')

def get_features(type='dbn'):
    pos_hindi_reviews = codecs.open("pos_hindi_final.txt", "r", encoding='utf-8', errors='ignore').read()
    neg_hindi_reviews = codecs.open("neg_hindi_final.txt", "r", encoding='utf-8', errors='ignore').read()
    pos_eng_reviews = codecs.open("pos_eng_final.txt", "r", encoding='utf-8', errors='ignore').read()
    neg_eng_reviews = codecs.open("neg_eng_final.txt", "r", encoding='utf-8', errors='ignore').read()
    pos_hinglish_reviews = codecs.open("pos_hinglish.txt", "r", encoding='utf-8', errors='ignore').read()
    neg_hinglish_reviews = codecs.open("neg_hinglish.txt", "r", encoding='utf-8', errors='ignore').read()
    documents = []
    documents_test = []
    pos_count = 0
    neg_count = 0
    pos_test_count = 0
    neg_test_count = 0

    for i in pos_hindi_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            pos_count += 1
    for i in neg_hindi_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            neg_count += 1
            
    for i in pos_eng_reviews.split(' .'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            pos_count += 1
    for i in neg_eng_reviews.split(' .'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            neg_count += 1

    for i in pos_hinglish_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents_test.append(data)
            pos_test_count += 1
    for i in neg_hinglish_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents_test.append(data)
            neg_test_count += 1
            
    vectorizer = TfidfVectorizer(lowercase=False, analyzer=word_tokenize)
    tfidf = vectorizer.fit_transform(documents)
    vectorizer_test = TfidfVectorizer(lowercase=False, analyzer=word_tokenize)
    tfidf_test = vectorizer_test.fit_transform(documents_test)
    featureset = tfidf.toarray()
    featureset_test = tfidf_test.toarray()
    positive_feature_set = featureset[0:pos_count]
    negative_set = featureset[pos_count:]
    positive_test_feature_set = featureset_test[0:pos_test_count]
    negative_test_set = featureset_test[pos_test_count:]
    finalset = []
    finalset_test = []
    for i in positive_feature_set:
        if type == 'simple':
            finalset.append([i, [1, 0]])
        else:
            finalset.append([i, 1])
    for i in negative_set:
        if type == 'simple':
            finalset.append([i, [0, 1]])
        else:
            finalset.append([i, 0])

    for i in positive_test_feature_set:
        if type == 'simple':
            finalset_test.append([i, [1, 0]])
        else:
            finalset_test.append([i, 1])
    for i in negative_test_set:
        if type == 'simple':
            finalset_test.append([i, [0, 1]])
        else:
            finalset_test.append([i, 0])

    finalset = np.array(finalset)
    finalset_test = np.array(finalset_test)
    random.shuffle(finalset)
    random.shuffle(finalset_test)
    test_size = 0.8
    train_size = 0.2
    training_size = int((1 - train_size) * len(finalset))
    testing_size = int((1 - test_size) * len(finalset_test))
    x_train = list(finalset[:, 0][:training_size])
    y_train = list(finalset[:, 1][:training_size])
    x_test = list(finalset_test[:, 0][testing_size:])
    y_test = list(finalset_test[:, 1][testing_size:])
    return x_train, y_train, x_test, y_test

In [4]:
get_features()

([array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.        , 0.        , 0.        , ..., 0.00494481, 0.03131711,
         0.03461365]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.        , 0.        , 0.        , ..., 0.00494481, 0.03131711,
         0.03461365]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.        , 0.        , 0.        , ..., 0.00494481, 0.03131711,
         0.03461365]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.        , 0.        , 0.        , ..., 0.00494481, 0.03131711,
         0.03461365]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.21248763, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.        , 0.        , 0.        , ..., 0.00494481, 0.03131711,
         0.03461365]),
  array([0., 0., 0

In [5]:
x_train, y_train, x_test, y_test = get_features()

In [6]:
x_test

[array([0.        , 0.        , 0.        , ..., 0.24396984, 0.        ,
        0.        ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.        , 0.        , 0.        , ..., 0.24396984, 0.        ,
        0.        ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.        , 0.        , 0.        , ..., 0.20216549, 0.        ,
        0.        ]),
 array([0.        , 0.        , 0.        , ..., 0.20216549, 0.        ,
        0.        ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.

In [13]:
def get_test_features(type='dbn'):
    pos_hinglish_reviews = codecs.open("pos_hinglish.txt", "r", encoding='utf-8', errors='ignore').read()
    neg_hinglish_reviews = codecs.open("neg_hinglish.txt", "r", encoding='utf-8', errors='ignore').read()
    documents = []
    
    pos_count = 0
    for i in pos_hinglish_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            pos_count += 1
    neg_count = 0
    for i in neg_hinglish_reviews.split('$'):
        data = i.strip('\n')
        if data:
            documents.append(data)
            neg_count += 1
            
            
    vectorizer = TfidfVectorizer(lowercase=False, analyzer=word_tokenize)
    tfidf = vectorizer.fit_transform(documents)
    featureset = tfidf.toarray()
    positive_feature_set = featureset[0:pos_count]
    negative_set = featureset[pos_count:]
    finalset = []
    for i in positive_feature_set:
        if type == 'simple':
            finalset.append([i, [1, 0]])
        else:
            finalset.append([i, 1])
    for i in negative_set:
        if type == 'simple':
            finalset.append([i, [0, 1]])
        else:
            finalset.append([i, 0])
    finalset = np.array(finalset)
    random.shuffle(finalset)
    test_size = 0.2
    testing_size = int((1 - test_size) * len(finalset))
    x_test = list(finalset[:, 0][:testing_size])
    y_test = list(finalset[:, 1][:testing_size])
    x_train = list(finalset[:, 0][testing_size:])
    y_train = list(finalset[:, 1][testing_size:])
    return x_test, y_test
    
get_test_features()

([array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
